services:
  - type: web
    name: rasa-hummingbird
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt && rasa train

    # Run both servers inside one container
    startCommand: |
      rasa run --enable-api --cors "*" --port 10000 &
      rasa run actions

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
