services:
  - type: web
    name: rasa-hummingbird
    env: docker
    plan: free
    dockerfilePath: rasa-server/Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

