services:
  - type: web
    name: rasa-hummingbird
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && rasa train
    startCommand: rasa run --enable-api --cors "*" --port 10000 --actions actions
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
